### PR TITLE
Use Swal.getHtmlContainer()

### PR DESCRIPTION
**Pull request by limonte**
Related to https://github.com/sweetalert2/sweetalert2/issues/1809

### CODE REVIEW

**Comment by toverux** [comment]
Nice! Thanks.
Why did you tagged it as `chore` commit? This could easily be a `fix` (with a [skip ci] tag eventually).

**Comment by limonte** [comment]
This PR isn't fixing anything. If you want to trigger the release, feel free to push the "fix: trigger release" commit.

**Comment by toverux** [comment]
I think that a fix is a valid tag here since this prevents the library from breaking in an eventual future SweetAlert2 upgrade. Semantically this is more a fix than a feat or chore. But now that I think about it, `refactor` seems even better, and does not trigger immediate releases.
But that's no problem, I was just being curious :)

**Comment by limonte** [comment]
Yup, `refactor:` seems to be the correct one in this case, thanks!

**Pull request merged**
