### PR TITLE
Update angular support

### PR DESCRIPTION
**Pull request by JulianoGTZ**
I've seen a vulnerability alert about the karma version. When I updated, I broke the angular scheme validation.

Then, I updated the angular references too.

### CODE REVIEW

**Comment by JulianoGTZ** [comment]
Thanks, @limonte. My experience with package-json.lock is terrible. A lot of conflicts between the team, and unexpected updates that sometimes broke some tests.

I will try using yarn.

**Comment by limonte** [comment]
@JulianoGTZ I can see that you rolled back changes in `package.lock`. I was thinking that it'll happen because dealing with angular deps isn't fun :)

I `cherry-pick`ed two commit from this PR to master, let's close this PR for now.

But anyways, thanks for trying to fix this!

**Comment by limonte** [comment]
the security issue is fixed by ed82a67cd31e57a2627308c1340951405d62e009

**Comment by JulianoGTZ** [comment]
yes @limonte. There were many errors with the typescript version and the peer dependencies. 

I need to study more about angular to deal with these errors.

**Pull request closed without merging**
