### PR TITLE
refactor: update to the latest sweetalert2 types

### PR DESCRIPTION
**Pull request by rafaelss95**
Based on changes in https://github.com/sweetalert2/sweetalert2/pull/1997 and previous related PRs.

~@toverux @limonte I'll leave it here as a draft to get your feedback on this.~

### CODE REVIEW

**Comment by toverux** [comment]
Thanks @rafaelss95, I'll wait for sweetalert2/sweetalert2#1997 to be merged and then I'll complete this PR.
As the changes of the two repos combined won't be backward-compatible (ngx-sweetalert will depend on symbols that didn't exist before), I'll also have to set a fix version requirement on the next minor/patch release of sweetalert2.

**Comment by limonte** [comment]
> Thanks @rafaelss95, I'll wait for [sweetalert2/sweetalert2#1997](https://github.com/sweetalert2/sweetalert2/pull/1997) to be merged and then I'll complete this PR.
> As the changes of the two repos combined won't be backward-compatible (ngx-sweetalert will depend on symbols that didn't exist before), I'll also have to set a fix version requirement on the next minor/patch release of sweetalert2.

@toverux [sweetalert2/sweetalert2#1997](https://github.com/sweetalert2/sweetalert2/pull/1997) is merged, please go ahead with this one :rocket:

**Comment by limonte** [comment]
Closing in favor of #164

**Comment by toverux** [comment]
New PR: #164 
@rafaelss95 I wasn't allowed to push to your repo to add commits, so I created a new branch and PR here based on your own branch, so your ownership on the first commit could be preserved ;)
If I remember right, you have to tick a box or something saying that you allow the maintainer of the upstream project to push to your repository.

**Pull request closed without merging**
