### PR TITLE
add demo link

### PR DESCRIPTION
**Pull request by kukac7**

### CODE REVIEW

**Comment by toverux** [comment]
Hello @kukac7,

I'm getting a blank page with an exception in the JS console:

```
engineblock-9b4c1b6dec327befdcdba0f801b5f53db7c391b2882d6932a44ab942da5b6dd5.js:2 Uncaught (in promise) TypeError: Cannot read property 'defaultExtension' of undefined
    at Object.generateConfig (engineblock-9b4c1b6dec327befdcdba0f801b5f53db7c391b2882d6932a44ab942da5b6dd5.js:2)
    at Object.start (engineblock-9b4c1b6dec327befdcdba0f801b5f53db7c391b2882d6932a44ab942da5b6dd5.js:3)
    at preview-fd6dc7c3c3d5bdd553cd.js:1
    at <anonymous>
generateConfig @ engineblock-9b4c1b6dec327befdcdba0f801b5f53db7c391b2882d6932a44ab942da5b6dd5.js:2
start @ engineblock-9b4c1b6dec327befdcdba0f801b5f53db7c391b2882d6932a44ab942da5b6dd5.js:3
(anonymous) @ preview-fd6dc7c3c3d5bdd553cd.js:1
Promise.then (async)
r @ preview-fd6dc7c3c3d5bdd553cd.js:1
window._preboot @ preview-fd6dc7c3c3d5bdd553cd.js:1
(anonymous) @ (index):11
(anonymous) @ (index):11
```

Also, I'm not sure to want adding a third-party link in the documentation. I don't know you so I can't have trust in a webpage I don't have the control on. Also, what's you demo for? SweetAlert2 demos can be found on the official website and I don't intend to show demos of this library _yet_.

Closing for now until I have a very good reason to consider this again.

**Comment by kukac7** [comment]
@toverux I think this is a @stackblitz bug.
I just did so: https://blog.angular.io/run-angular-cli-repos-directly-in-your-browser-41332fd80901
I think a demo page would be nice to see how it works.
that's all I wanted. :)

**Comment by toverux** [comment]
Oh, ok, now that there is not longer just a strange link and a lack of explanation, it's much better :)

I think that we can share the StackBlitz link as a demo + template to make bug reports (StackBlitz seems to be far better than codepen/jsfiddle for Angular).

Will think about how I present things, maybe add example in `demo/` and merge later. Thanks for your help 🙂

**Comment by kukac7** [comment]
@toverux yes, I gave a bad link.

thanks!

**Pull request closed without merging**
