### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by kjra1707**
Update angular version 17

### CODE REVIEW

**Comment by GUlbricht** [comment]
Can this get merged soon?

**Comment by D-Biela** [comment]
Still waiting :-/

**Review by chrisepm — APPROVED** [review]
Ready to be merge.

**Comment by FGO-LPCR** [comment]
Any news? @limonte @toverux

**Comment by usarskyy** [comment]
@chrisepm could you please merge this PR? It's been a while since the PR was created

**Review by limonte — APPROVED** [review]

**Comment by limonte** [comment]
Sorry for the delay everyone 🙌

**Pull request merged**
