### PR TITLE
Enable tests in CI

### PR DESCRIPTION
**Pull request by limonte**
Use `ChromeHeadless` in CI enviromnent.

Connected to #139

### CODE REVIEW

**Comment by limonte** [comment]
Tests are failing with the `NullInjectorError: No provider for SweetAlert2LoaderService!` exception.

**Comment by limonte** [comment]
ping @toverux

**Comment by toverux** [comment]
That'll probably work with you latest commit, but I was about to push a bigger modification!

**Comment by limonte** [comment]
> That'll probably work with you latest commit, but I was about to push a bigger modification!

oops, sorry!

**Comment by limonte** [comment]
feel free to override my changer by using `git push --force`

**Comment by toverux** [comment]
No problem! Thanks for helping with this :)

**Pull request merged**
