### PR TITLE
update to angular 7

### LINKED ISSUE #99: Purportedly incompatible with Angular 7
I am in process of manually (non-ng cli) upgrading an Angular project.  For Angular 7 `yarn install`, I get this:

`@toverux/ngx-sweetalert2@4.0.0" has incorrect peer dependency "@angular/core@^5.0.0 || ^6.0.0"
@toverux/ngx-sweetalert2@4.0.0" has incorrect peer dependency "@angular/common@^5.0.0 || ^6.0.0"`

It seems this requires a simple package.json tweak and tagged release of 4.0.1 or similar to get it compatible with 7.  Thoughts?  Thanks!

### PR DESCRIPTION
**Pull request by fscherwi**
Fix #99

### CODE REVIEW

**Comment by toverux** [comment]
Oh! Yeah!
I'm in vacations right now (didn't knew about the Angular release) but I'll be back in, like, two days. I'll test, then merge it asap. Thanks!

**Comment by sergio-new-developer** [comment]
Hello, @fscherwi!
When you will update project with angular 7?
Thank you

**Comment by efritz** [comment]
Any update on this?

**Comment by sagrawal31** [comment]
When the version 4.1.0 is going to be released?

**Comment by limonte** [comment]
Unfortunately, the automated releasing process is broken https://github.com/sweetalert2/ngx-sweetalert2/issues/104

@toverux can you maybe make the release from you machine?

**Pull request merged**
